config/routes.rb
CourseMash::Application.routes.draw do
  devise_for :users

  root :to => "static_pages#home"

  get 'all_courses' => "courses#all_courses", as: 'all_courses' 
  get 'course/:name' => "courses#show", as: 'course'
  get 'my_courses' => "courses#my_courses", as: 'my_courses'
  post 'course/add' => "courses#add", as: 'course_add' 
  get 'course/remove/:course_id' => "courses#remove", as: 'course_remove' 

  get 'user' => "user#all_users", as: 'all_users' 
  get 'user/:username' => "user#show", as: 'user' 

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :title, :body
  has_many :course_selections
  has_many :users, :through=> :course_selections
end

app/models/course_selection.rb
class CourseSelection < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :profile_pic_url
  # attr_accessible :title, :body

  has_many :course_selections
  has_many :courses, :through=> :course_selections

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)

  	flash.notice = 'You are successfully signed in! Please add your courses!'

  	my_courses_path

  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_filter :authenticate_user!

	def all_courses
		@all_courses = Course.all
	end

	def show

		course_count = current_user.courses.count

		if (course_count < 5)
			flash.alert = 'Sorry, but in order to view who is enrolled in "' + Course.find(params[:name]).title + '" you must add atleast 5 of your own courses.'
			redirect_to :action => 'my_courses'
		else
			@course = Course.find(params[:name])		
		end
	end

	def my_courses
	end

	def add
		flash_notice = ''


    if params[:courses].nil?
	  flash.alert = "You did not select any courses, please press the checkbox next to all of the courses you are registered for. Then press 'Add Selected Courses'"
      redirect_to :action => 'my_courses'
    
    else

      params[:courses].each_key do |key|
        
        course_to_add = Course.find(key)
        if (current_user.courses.where(id: key)).empty?

		  	if (current_user.courses << course_to_add)
		       flash_notice = flash_notice + ' \'' + course_to_add.title + '\'' + ' Successfully Added <br/>'
		  	end
		else
	  		flash_notice = flash_notice + ' You are already enrolled in ' + '\'' + course_to_add.title + '\' <br/>'
	  	end

	  end
	  
	  flash.alert = flash_notice
      redirect_to :action => 'my_courses'
    
    end
      
  	end	

	def remove
		course_to_remove = Course.find(params[:course_id])
		
		if (current_user.courses.delete(course_to_remove))

			flash.alert = '\'' + Course.find(params[:course_id]).title + '\'' + ' Removed from your courses'
			redirect_to :action => 'my_courses'
		else
			flash.alert = '\'' + Course.find(params[:course_id]).title + '\'' + ' Could not be deleted'
			redirect_to :action => 'my_courses'
		end
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	before_filter :authenticate_user!

	def all_users
		@all_users = User.all.delete_if {|user| user == current_user} 
	end

	def show
		course_count = current_user.courses.count

		if (course_count < 5)
			flash.alert = 'Sorry, but in order to view the courses that this person is enrolled in you, must add atleast 5 of your own courses'
			redirect_to my_courses_path
		else
		
			@user = User.find(params[:username])		
		
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/courses/all_courses.html.erb
<% content_for :title do %>
  All EC Courses
<% end %>

<h2>
	All Courses
</h2>
This is a list of all EC courses.
<hr>


<% @courses_to_display = @all_courses %>

<%= render "courses/shared/list_courses"%>

app/views/courses/my_courses.html.erb
<% content_for :title do %>
  <%= current_user.firstname %>'s Courses
<% end %>



<h2>
	<%= current_user.firstname %>'s Registered Courses
</h2>

<hr>

	<% if current_user.courses.count == 0 %>
		
		You have not added any courses. Please add atleast 5 courses using the table below in order view course enrollment. 

	<% else %>
		<%= render "courses/shared/my_courses_table"%>
	<% end %>

<hr>

<br/>
<br/>

<!-- add new courses -->

<h2>
	Add New Courses
</h2>

<a href='http://beech.hbs.edu/preregAddDrop/student/' target='_blank' title='Takes you to your HBS EC classes page so you can select them below'>
	View your registered HBS EC courses 
</a>

<br/>

Please click the checkbox next to each course you are registered for. Then press the 'Add selected course button'. Be sure to choose the right section.



<br/>
Hint: Use the search box on the right to easily find your courses. 

<hr>
<%= render "courses/shared/user_action_all_courses_table"%>

app/views/courses/shared/_list_courses.html.erb
<% if @table_id.nil? %>
 <% @table_id = 'course_list_id' %>
<% end %>

<table id="<%= @table_id %>">
  <thead>
    <tr>
      <th>Course Title</th>

      <th>Faculty</th>

      <th>Section</th>

      <th>Day</th>

      <th>Time</th>

      <th>Location</th>

      <th>Code</th>

      <th>Term</th>

      <th>Quarter/Credits</th>

    </tr>
  </thead>  

  <tbody>
    <% @courses_to_display.each do |course| %>
      <tr>

        <td>
      <%= link_to course_path(course), :title =>"See who is enrolled in this course" do %>
        <%= course.title %>
      <% end %>
        </td>

        <td>
      <%= course.faculty %>
        </td>

        <td>
      <%= course.section %>
        </td>

        <td>
      <%= course.day %>
        </td>

        <td>
      <%= course.time %>
        </td>

        <td>
      <%= course.location %>
        </td>

        <td>
      <%= course.code %>
        </td>

          <td>
      <%= course.term %>
        </td>

          <td>
      <%= course.quarter_credits %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<script>
  
  $('#<%= @table_id %>').dataTable(
        {
          "bPaginate": false,
          "aoColumnDefs": [

            { "sWidth": "30%", 'aTargets': [ 0 ],
            },

            { "sWidth": "10%", 'aTargets': [ 1 ],
            },

                          ],
        });
    

</script>

app/views/courses/shared/_list_users.html.erb
<div style='width:300px' >
  <table id="user_list_id">
    <thead>
      <tr>
        <th>Name</th>

      </tr>
    </thead>  

    <tbody>
      <% @users_to_display.each do |user| %>
        <tr>

          <td>
      			<%= link_to user_path(user) do %>
              <span title='See all of the courses that <%= user.firstname %> is taking' >
        				<%= user.firstname %> <%= user.lastname %>
              </span>
      			<% end %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  
  $('#user_list_id').dataTable(
        {
          "bPaginate": false,
          "aoColumnDefs": [

            { "sWidth": "70px", 'aTargets': [ 0 ],
            },


                          ],
        });
    

</script>

app/views/courses/shared/_my_courses_table.html.erb
<table id="my_courses_tables">
  <thead>
    <tr>
      <th>Course Title</th>

      <th>Enrolled Students</th>

      <th>Faculty</th>

      <th>Section</th>

      <th>Term</th>
  
      <th>Remove Course?</th>

    </tr>
  </thead>  

  <tbody>
    <% current_user.courses.all.each do |course| %>
      <tr>

        <td>
    			<%= link_to course_path(course), :title =>"See who is enrolled in this course" do %>
			     	<%= course.title %>
	     		<% end %>
        </td>

        <td>
            <div style='height:80px; overflow:auto; padding-left:5px;'>
              <% course.users.each do |registered_students| %>

                <%= link_to user_path(registered_students) do %>
                  <span title='See all of the courses that <%= registered_students.firstname %> is taking' >
                    <%= registered_students.firstname %> <%= registered_students.lastname %>
                  </span>
                <% end %>

                <br/>

              <% end %>
          </div>

        </td>



        <td>
			<%= course.faculty %>
        </td>

        <td>
			<%= course.section %>
        </td>

        <td>
      <%= course.term %>
        </td>


        <td>
    			<a href='/course/remove/<%= course.id %>' title='Remove this course from my list'>
			   	Remove Course
		    	</a>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<script>
  
  $('#my_courses_tables').dataTable(
        {
          "bPaginate": false,
          "aoColumnDefs": [
            { "sWidth": "30%", 'aTargets': [ 0 ],
            },

            { "sWidth": "20%", 'aTargets': [ 1 ],
            },

            { 'bSortable': false, 'aTargets': [ 5 ],
            }

                          ],
        });

</script>

app/views/courses/shared/_user_action_all_courses_table.html.erb
<%= form_tag("/course/add", method: "post",:id => 'checked_courses') do %>

  <button type="submit" class="btn-large btn-success" title="Add the selected courses below to your registered courses">Add selected courses
  </button>


<table id="add_new_courses_id">
  <thead>
    <tr>
      <th>Add Course</th>

      <th>Course Title</th>

      <th>Faculty</th>

      <th>Section</th>

      <th>Day</th>

      <th>Time</th>

      <th>Location</th>

      <th>Code</th>

      <th>Term</th>

      <th>Quarter/Credits</th>
  
    </tr>
  </thead>  

  <tbody>

    <% Course.all.each do |course| %>
      <tr>
        <td>
          <input name="courses[<%= course.id %>]" type="checkbox" />


        </td>

        <td>
      <%= link_to course_path(course), :title =>"See who is enrolled in this course" do %>
        <%= course.title %>
      <% end %>
        </td>

        <td>
      <%= course.faculty %>
        </td>

        <td>
      <%= course.section %>
        </td>

        <td>
      <%= course.day %>
        </td>

        <td>
      <%= course.time %>
        </td>

        <td>
      <%= course.location %>
        </td>

        <td>
      <%= course.code %>
        </td>

          <td>
      <%= course.term %>
        </td>

          <td>
      <%= course.quarter_credits %>
        </td>

      </tr>
    <% end %>

  </tbody>
</table>

<br/>
<br/>

  <button type="submit" class="btn-large btn-success" title="Add the selected courses below to your registered courses">
    Add selected courses
  </button>

<% end %>

<script>
  $('#add_new_courses_id').dataTable(
        {
          "bPaginate": false,
          "aoColumnDefs": [

            { "sWidth": "40%", 'aTargets': [ 1 ],
            },

            { "sWidth": "20%", 'aTargets': [ 2 ],
            },

            { 'bSortable': false, 'aTargets': [ 0 ],
            }

                          ],
        });

</script>

app/views/courses/show.html.erb
<% content_for :title do %>
  <%= @course.title %>
<% end %>


<h3>
	<%= @course.title %>
</h3>


<table>
	<tr>
		<td>
			Faculty:
		</td>
		<td>
			<%= @course.faculty %>
		</td>
	</tr>		

	<tr>
		<td>
			Section:
		</td>
		<td>
			<%= @course.section %>
		</td>
	</tr>

	<tr>
		<td>
			Day:
		</td>
		<td>
			<%= @course.day %>
		</td>
	</tr>

	<tr>
		<td>
			Time:
		</td>
		<td>
			<%= @course.time %>
		</td>
	</tr>

	<tr>
		<td>
			Location:
		</td>
		<td>
			<%= @course.location %>
		</td>
	</tr>

	<tr>
		<td>
			Code:
		</td>
		<td>
			<%= @course.code %>
		</td>
	</tr>

	<tr>
		<td>
			Term:
		</td>
		<td>
			<%= @course.term %>
		</td>
	</tr>

	<tr>
		<td>
			Quarter/Credits:
		</td>
		<td>
			<%= @course.quarter_credits %>
		</td>
	</tr>


</table>

<hr>

<h3>
Registed Students:
</h3>

<% @users_to_display = @course.users %>

<% if @users_to_display.count == 0 %>
	
	<br/>	
	We do not have any record of enrollment yet.
	<br/>

<% else %>

	<%= render "courses/shared/list_users"%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--
  <link rel="icon" 
      type="image/png" 
      href="/assets/Favicon2_v1.png">
	-->

  <title>
    <%= yield(:title) %>
  </title>

  <%= yield(:head) %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <script src="http://connect.facebook.net/en_US/all.js"></script>
  <script src="<%= ENV['domain'] %>/jquery.timeago.js" type="text/javascript"></script>
  <script src="<%= ENV['domain'] %>/linkify.js" type="text/javascript"></script>

  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">

  <link href='http://fonts.googleapis.com/css?family=Anonymous+Pro&subset=latin' rel='stylesheet' type='text/css'>



  <%= csrf_meta_tags %>


</head>
<body>

    <div class="navbar navbar-fixed-top">
    <div class="navbar-inner nav_height">
      <div class="container">
        <a href="<%= root_url %>" class="brand"> 
          <span title='Go to the Hogwarts Business School Homepage'>
            Hogwarts Business School Friend Finder
          </span>
        </a>

        &nbsp
        &nbsp


        <% if user_signed_in? %>
          <ul class="nav padding-top">

          	<button class="btn btn-success" onClick="window.location='<%= my_courses_path %>'" type="button"> 
				My Courses
			</button>

	        &nbsp

      <button class="btn btn-success" onClick="window.location='<%= all_users_path %>'" type="button">
        See Friend's Common Courses
      </button>

          &nbsp

			<button class="btn btn-success" onClick="window.location='<%= all_courses_path %>'" type="button">
				All Courses
			</button>




          </ul>
        <% end %>

        <ul class="nav pull-right">
          <% if user_signed_in? %>

            <div id="fat-menu" class="dropdown">
              <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">

                <table>
                  <tr>
                    <td>                
                      &nbsp <%= ' ' + current_user.firstname + ' ' + current_user.lastname + ' ' %>
                      <b class="caret"></b>
                    </td>
                  </tr>
                </table>

              </a>

              <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                   
                     <li><%= link_to "Edit Account Settings", edit_user_registration_path %>
                     </li>
                   

                  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                  </li>

              </ul>
            </div>

          <% else %>

			<button class="btn btn-success" onClick="window.location='<%= new_user_registration_path %>'" type="button">
				Sign Up
			</button>

			<button class="btn btn-success" onClick="window.location='<%= new_user_session_path %>'" type="button">
				Login 
			</button>
            	

          <% end %>

        </ul>
      </div>
    </div>
  </div>
	
	<br/>
	<br/>

  <div class="container">
    
    <br/>
    <br/>

    <% if notice %>
      <p class="notice"><%= notice.html_safe %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert.html_safe %></p>  
    <% end %>

    <%= yield %>
    
  </div>

  		<%= render "static_pages/shared/footer"%>

</body>


</html>
<script>
$('.dropdown-toggle').dropdown();
$( '*' ).qtip(
        {
          style: {
            classes: 'qtip-dark qtip-shadow',
                }
        }
        );
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43336836-1', 'hogwartsbschool.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/static_pages/home.html.erb
<% content_for :title do %>
  Hogwarts Business School Friend Finder
<% end %>


<div class='homepage_hero'>
	<center>
		<br/>
		<h2>
			Hogwarts Business School Friend Finder
		</h2>
	
		<br/>
		<h4>
			A simple tool for finding out who's in your class.
		</h4>
	

		<br/>	

	    <% if user_signed_in? %>
	    <% else %>

	    	Please 

			<button class="btn btn-success" onClick="window.location='<%= new_user_registration_path %>'" type="button">
				Sign Up
			</button>

			 or 

			<button class="btn btn-success" onClick="window.location='<%= new_user_session_path %>'" type="button">
				Login 
			</button>

			in order to get started!
			<br/>
		<% end %>
	</center>
	<br/>
</div>

<br/>
	<ul>
		<strong>
		<li>
		    <% if user_signed_in? %>
	    		<button class="btn btn-success" onClick="window.location='<%= my_courses_path %>'" type="button"> 
					My Courses
				</button>

				 - See all of the courses you are registered for, and who's in them.
	    	<% else %>
	    		See who's in the courses you're registered for.
    		<% end %>
		</li>

		<br/>

		<li>
		    <% if user_signed_in? %>
				<button class="btn btn-success" onClick="window.location='<%= all_courses_path %>'" type="button">
					All Courses
				</button>

		 			- Browse through all of HBS's second year courses to see who's in them.
	    	<% else %>
	    		Browse through all of HBS's EC courses and see who's in them.
    		<% end %>
		</li>

		<br/>

		<li>
		    <% if user_signed_in? %>

				<button class="btn btn-success" onClick="window.location='<%= all_courses_path %>'" type="button">
					See Friends Courses
				</button>

					- Find your friends and see what courses they're in.
			<% else %>
				Find your friends and see what courses they're in.
			<% end %>
		</li>
		</strong>
	</ul>
<br/>
<br/>

<hr/>

We use crowd sourced data to populate course information, therefore the list of students in a particular course may not be accurate. For entertainment purposes only.

<br/>


<br/>

<hr>
<h2>
	Thank You for trying it out!
</h2>

I'd love to hear what you think about this. Please email me - <a href = "mailto:?to=varun.bhartia@gmail.com">
	Varun Bhartia - varun.bhartia@gmail.com
</a>

<br/>
	<h5>
		Not affliated with or endorsed by  Harvard Business School in any way. 
	</h5>

app/views/static_pages/shared/_footer.html.erb
<div class='container'>


</div>

app/views/user/all_users.html.erb
<% content_for :title do %>
  All Registered Students
<% end %>


<h3>
  All Registered Students
</h3>

Please click on a student to see all courses the student is taking and what courses you have in common.

<br/>
<br/>

<% @users_to_display = @all_users %>

<div style='width:100%' >
  <table id="user_list_id">
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of Courses In Common</th>
        <th>Common Courses</th>
      </tr>
    </thead>  

    <tbody>
      <% @users_to_display.each do |user| %>
        <tr>

          <td>
      			<%= link_to user_path(user) do %>
              <span title='See all of the courses that <%= user.firstname %> is taking' >
        				<%= user.firstname %> <%= user.lastname %>
              </span>
      			<% end %>
          </td>

          <td>
      			<%= link_to user_path(user) do %>
	              <div style='text-align:center' title='See all of the courses that <%= user.firstname %> is taking' >

      				<%= (user.courses & current_user.courses).count %>
  				  </div>
  				<% end %>	
          </td>

          <td>
  			<div style='height:70px; overflow:auto; padding-left:5px;'>
	        	<% (user.courses & current_user.courses).each do |mututal_course| %>

                	<%= link_to course_path(mututal_course) do %>
                  		<span title='See all of the students registered for <%= mututal_course.title %>' >
                    		<%= mututal_course.title %> 
                  		</span>
                	<% end %>
 	                <br/>
				<% end %>
          	</div>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  
  $('#user_list_id').dataTable(
        {
          "aaSorting": [[ 1, "desc" ]],
          "bPaginate": false,
          "aoColumnDefs": [

            { "sWidth": "150px", 'aTargets': [ 0 ],
            },
            { "sWidth": "100px", 'aTargets': [ 1 ],
            },


                          ],
        });
    

</script>

app/views/user/my_courses.html.erb
<!-- Shows the Current Users Courses -->

app/views/user/show.html.erb
<!-- Shows the courses for a particular user -->
<% content_for :title do %>
  <%= @user.firstname %>'s Courses
<% end %>

<h3>
	Courses you have in common with <%= @user.firstname %>:
</h3>

<hr/>

	<% @table_id = 'common_courses' %>

	<% @courses_to_display = (@user.courses & current_user.courses) %>

	<% if @courses_to_display.count == 0 %>
		
		Sorry - you do not have any courses in common 

	<% else %>
		<%= render "courses/shared/list_courses"%>
	<% end %>

<br/>
<br/>
<br/>
<br/>



<h3>
	<%= @user.firstname %> <%= @user.lastname %>'s courses:
</h3>


<hr>

<% @table_id = 'all_courses' %>

<% @courses_to_display = @user.courses %>

<%= render "courses/shared/list_courses"%>